/run/initialize
/control/verbose 0

/analysis/setFileName test.root

/generator/setProfileFileName EAR1_183.5_E1_1.e-3_E2_1.e9.root
/generator/setProfileHistName histfluka
/generator/setFluxFileName plots_Comp.root
/generator/setFluxHistName hFlux_EAR1
/generator/setTOFLength 183.5 # m

/generator/setFluxLowerLimit  5 # MeV
/generator/setFluxUpperLimit 10 # MeV
/run/printProgress   10
/run/beamOn         100
