/run/initialize
/control/verbose 0

/analysis/setFileName EAR2_19.1.root

/generator/setProfileFileName EAR2_19.1_E1_1.e-3_E2_1.e9.root
/generator/setProfileHistName histfluka
/generator/setFluxFileName plots_Comp.root
/generator/setFluxHistName hFlux_EAR2
/generator/setTOFLength 19.1 # m

# Simulate 3600 seconds with different energy ranges
/generator/setFluxLowerLimit   5 # MeV
/generator/setFluxUpperLimit 100 # MeV
/run/printProgress  1000000
/run/beamOn       328145000
